name: Deploy Serverless Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check the cloned directory
        run: | 
          ls
          pwd

      - name: Install Serverless Framework
        run: npm install -g serverless@3.29.0

      - name: Deploy with Serverless
        run: serverless deploy